debug:
  update_interval: 5s

text_sensor:
 # Wifi text_sensor
  - platform: wifi_info
    ip_address:
      name: "9909 ESP IP Address"
      state_topic: ${prefix}/${subtopic}/99_Info/09_IP_Address
      update_interval: 300s

 # ESP Uptime text_sensor
  - platform: template
    name: "9904 ESP Uptime"
    id: uptime_human
    state_topic: ${prefix}/${subtopic}/99_Info/04_ESP_Uptime

 # DEBUG text_sensor
  - platform: debug
    device:
      name: "990005 Device Info"
      state_topic: ${prefix}/${subtopic}/99_Info/00_Debug/05_Device_Info
    reset_reason:
      name: "990006 Reset Reason"
      state_topic: ${prefix}/${subtopic}/99_Info/00_Debug/06_Reset_Reason

sensor:
 # ESP Uptime sensor
  - platform: uptime
    name: "9904 ESP Uptime (s)"
    id: uptime_sensor
    update_interval: 10s
    state_topic: ${prefix}/${subtopic}/99_Info/04_ESP_Uptime/seconds
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

 # WiFi Signal db sensor
  - platform: wifi_signal
    name: "9903 ESP WiFi Signal dBm"
    id: wifi_signal_db
    update_interval: 10s
    state_topic: ${prefix}/${subtopic}/99_Info/03_WiFi_Signal/db

 # WiFi Signal % sensor
  - platform: copy
    source_id: wifi_signal_db
    name: "9903 ESP WiFi Signal %"
    filters:
    - delta: 5
    - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    state_topic: ${prefix}/${subtopic}/99_Info/03_WiFi_Signal

 # ESP debug sensor
  - platform: debug
    free:
      name: "990001 free Heap"
      filters:
        - multiply: 0.001024
        #- delta: 5
      accuracy_decimals: 3
      unit_of_measurement: "kB"
      state_topic: ${prefix}/${subtopic}/99_Info/00_Debug/01_free_Heap
    block:
      name: "990002 Largest contiuous free RAM Block"
      filters:
        - multiply: 0.001024
        - delta: 50
      accuracy_decimals: 3
      unit_of_measurement: "kB"
      state_topic: ${prefix}/${subtopic}/99_Info/00_Debug/02_Largest_free_Block
    loop_time:
      name: "990004 Loop Time"
      filters:
        - delta: 5
      unit_of_measurement: "ms"
      state_topic: ${prefix}/${subtopic}/99_Info/00_Debug/04_Loop_Time

button:
 # ESP restart button
  - platform: restart
    name: "9799 restart ESP"
    id: "restart_ESP"
    state_topic: ${prefix}/${subtopic}/97_Buttons/99_ESP_restart
    command_topic: ${prefix}/${subtopic}/97_Buttons/99_ESP_restart

esphome:
  on_boot:
    priority: -100
    then:
# create command topics for ESP
      - mqtt.publish:
          topic: ${prefix}/${subtopic}/97_Buttons/99_ESP_restart
          payload: "PRESS "